"""
Reference data loading: TOC codes and STANOX location names.

Both lookups degrade gracefully if the source file is absent — the app still
starts and raw codes are displayed instead of resolved names.

TOC reference:  toc_ref.csv  (columns: toc_id, toc_name)
                Generated by scripts/fetch_toc_ref.py from the Open Rail Data wiki.

STANOX reference: CORPUSExtract.json  (Network Rail open data portal)
                  Structure: {"TIPLOCDATA": [{STANOX, NLCDESC, ...}, ...]}
                  We use the NLCDESC field (full location name).

Both files are loaded from REFERENCE_DATA_DIR (env var, defaults to cwd).
"""

import csv
import json
import logging
import os
from pathlib import Path

logger = logging.getLogger(__name__)


def _ref_dir() -> Path:
    """Return the directory to search for reference files."""
    env_path = os.environ.get("REFERENCE_DATA_DIR", "")
    if env_path:
        return Path(env_path)
    return Path.cwd()


class ReferenceData:
    def __init__(self):
        self.toc_names: dict[str, str] = {}
        self.stanox_names: dict[str, str] = {}
        self.toc_ref_loaded: bool = False
        self.stanox_ref_loaded: bool = False

    def load_all(self) -> None:
        self._load_toc_ref()
        self._load_stanox_ref()

    # ------------------------------------------------------------------
    # Loaders
    # ------------------------------------------------------------------

    def _load_toc_ref(self) -> None:
        path = _ref_dir() / "toc_ref.csv"
        if not path.exists():
            logger.warning("toc_ref.csv not found at %s — TOC codes will display as raw IDs.", path)
            return
        try:
            with path.open(newline="", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                loaded = 0
                for row in reader:
                    toc_id = str(row.get("toc_id", "")).strip()
                    toc_name = str(row.get("toc_name", "")).strip()
                    if toc_id:
                        self.toc_names[toc_id] = toc_name
                        loaded += 1
            self.toc_ref_loaded = True
            logger.info("toc_ref.csv loaded: %d TOC codes.", loaded)
        except Exception as exc:
            logger.warning("Failed to load toc_ref.csv: %s — TOC codes will display as raw IDs.", exc)

    def _load_stanox_ref(self) -> None:
        # Look in ref dir first, then in the "Reference data" subdirectory alongside the script.
        candidates = [
            _ref_dir() / "CORPUSExtract.json",
            Path(__file__).parent / "Reference data" / "CORPUSExtract.json",
        ]
        path = next((p for p in candidates if p.exists()), None)
        if path is None:
            logger.warning(
                "CORPUSExtract.json not found — STANOX codes will display as raw IDs. "
                "Download from Network Rail open data portal and place in %s.",
                _ref_dir(),
            )
            return
        try:
            with path.open(encoding="utf-8") as f:
                data = json.load(f)
            records = data.get("TIPLOCDATA", [])
            loaded = 0
            for record in records:
                stanox = str(record.get("STANOX", "")).strip()
                # Use NLCDESC (full name). Fall back to TIPLOC if blank.
                name = str(record.get("NLCDESC", "")).strip()
                if not name:
                    name = str(record.get("TIPLOC", "")).strip()
                if stanox and name:
                    self.stanox_names[stanox] = name
                    loaded += 1
            self.stanox_ref_loaded = True
            logger.info("CORPUSExtract.json loaded from %s: %d STANOX entries.", path, loaded)
        except Exception as exc:
            logger.warning("Failed to load CORPUSExtract.json: %s — STANOX codes will display as raw IDs.", exc)

    # ------------------------------------------------------------------
    # Lookups  (always return a string — never None)
    # ------------------------------------------------------------------

    def resolve_toc(self, toc_id: str) -> str:
        """Return operator name for toc_id, or raw toc_id if not found."""
        return self.toc_names.get(str(toc_id).strip(), toc_id)

    def resolve_stanox(self, stanox: str) -> str:
        """Return location name for STANOX code, or raw code if not found."""
        return self.stanox_names.get(str(stanox).strip(), stanox)
